### PR TITLE
Hac 70 monthly.funding

### PR DESCRIPTION
**Pull request by ticooo95**
issue #135

### CODE REVIEW

**Comment by alayham** [comment]
Acceptance criteria:
Table of all (funding) closed projects for a set time period. Organization, bank account, project name and amount.

This needs to be improved by adding a date filter, and figuring out how to show the projects that were closed in a specific period.

**Comment by ticooo95** [comment]
yes. But this as well should be implemented on the back end. and we again we just call it the filtering method from the -said to be done- API.
Regarding the fields, i'll edit them now

**Comment by ticooo95** [comment]
aha. i think i got your comment wrong.
i think another field should be added in the backend which has the actual (closing) date of a project. And our task add a filter Date in the closed projects page.

**Comment by alayham** [comment]
I suggest solving the "closing a project" feature like this:
**if the project reaches 100% of funding, it closing date is changed to now, which is logical according to Daniels definition of closed projects.**
this way, all closed projects will be in the past, when you run the report, and you will know exactly when a project was closed. your filter will be on the closing date, and the donor team can add an action to set the closing date when the project reaches 100%.

**Comment by alayham** [comment]
here is my suggestion for solving this issue. 
https://github.com/IvanCybercom/Hackademy-IV-frontend/tree/HAC-admin-reporting-module
if you like the code, feel free to use it.

**Comment by albannurkollari** [comment]
Due to merging conflicts on this branch, I hereby am closing this pull request, but, keeping the branch for tracking work history. Please refer to [https://github.com/IvanCybercom/Hackademy-IV-frontend/tree/HAC-13-700/Admin-Reports-Closed-Projects](Admin Reports: Closed Projects) for the latest updates following this branch work.

**Pull request closed without merging**
