### PR TITLE
Shared Module Update Request!

### PR DESCRIPTION
**Pull request by albannurkollari**
Please review the change. I think we all agreed/agreeing on adding another shared module to the shared.module.ts file.

**NOTE**: Review asap because we would be able to merge it to origin/development branch and continue with our tasks.

### CODE REVIEW

**Comment by neirasah** [comment]
agreed.

**Comment by Mhd-Yaseen** [comment]
RTBM

**Comment by sheon** [comment]
Agreed!

**Comment by AdiHasani** [comment]
Agreed.

**Comment by MhdBarazi** [comment]
agreed

**Comment by ticooo95** [comment]
10 4

**Comment by sammed** [comment]
RTBM

**Comment by khaleids** [comment]
RTBM

**Pull request merged**
