### PR TITLE
Hac 13 007/project list update

### PR DESCRIPTION
**Pull request by ticooo95**
issure #139

### CODE REVIEW

**Comment by alayham** [comment]
I still think that there should be a better solution for the "closed project" topic.

According to the product owner, the project is closed when funding is complete or the funding period is closed. the solution in this Pull request does not filter projects according to the business criteria, but creates a new property and requires the product owner to close projects manually.

**Comment by ticooo95** [comment]
the actual functionality of closing a project should be done on the backend

**Comment by ticooo95** [comment]
we're just going to "call" it , and filter them

**Comment by ticooo95** [comment]
@alayham

**Comment by alayham** [comment]
I have no idea how this new field will be updated and who is going to do that. If it was for me, I would solve the problem without adding this new field as I said yesterday. 
It is your code. If you are sure, feel free to go ahead...

**Comment by ticooo95** [comment]
on the back-end there can be triggers designed for updating fields on regular bases or as soon as a field is changed. So the project can be checked every day to find out if it is the due date. for reaching the goal in funding, as soon as a transaction is made and the raised funding is changed the open field can be changed if it has reached the goal. this should be done on the back-end and we just filter those which are open or closed or all. 
Otherwise we need to implement this wherever the projects are gonna be shown, admin and user, which to me is not efficient.

**Pull request merged**
