### PR TITLE
event changed into activity. getSelectedProject now returns an array …

### PR DESCRIPTION
**Pull request by sheon**
The getSelectedProject service now returns an array of observables. the first item is the project info and the second is the project activities info. The event has been renamed to activity therefore the related files and interfaces have been renamed as well.

### CODE REVIEW

**Comment by alayham** [comment]
I recommend deprecation the old interface and json files instead of removing them to give other people who use them some time to update their code.

If you merge this, you might break other people's code.

**Comment by sheon** [comment]
Al, the event.json is part of this sprint and I changed it as we faced a problem since I was using a reserved keyword Event. Moreover, nobody has used it yet. Thus for this special occasion it wont break anyone's code.

**Comment by alayham** [comment]
It is a good programming practice to deprecate interfaces, declarations, properties, methods, classes, and other code before removing them.
It might not harm anybody in this specific case, but for the sake of best practices, I would deprecate before removing. This is your code, so do as you wish.

**Comment by sheon** [comment]
Ok, I understand what you say but we are going to use it now. So I need to merge it.
But PLZ let me know how I should deprecate piece of code so I can use it next time!
Maybe open an issue to discuss it!!!!!!!

**Comment by sheon** [comment]
@AdiHasani : I agree, we should start following the best practice.

**Pull request merged**
